---
- name: copy a index.html
  copy:
   src: /opt/ansible/index.html
   dest: /var/www/html
   mode: 0666

- name: ensure the default Apache port is {{ port }}
  lineinfile:
   path: /etc/httpd/conf/httpd.conf
   regexp: '^Listen '
   insertafter: '^#Listen '
   line: 'Listen {{ port }}'
  when: ansible_os_family ==  "RedHat"
  notify: restart httpd service

- name: ensure the default Apache port is {{ port }} on ubuntu
  lineinfile:
   path: /etc/apache2/ports.conf
   regexp: '^Listen '
   insertafter: '^# /etc/apache2/sites-enabled/000-default.conf'
   line: 'Listen {{ port }}'
  when: ansible_os_family == "Debian"
  notify: restart apache2

